name: foodistan
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.3
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^3.1.0
  firebase_core : ^1.6.0
  page_transition:
  flutter_svg: ^0.23.0+1
  auto_size_text: ^3.0.0
  pin_code_fields: ^7.3.0
  otp_text_field: ^1.1.1
  sizer: ^2.0.15
  intl_phone_field: ^2.1.0
  readmore: ^2.1.0
  font_awesome_flutter: ^9.2.0
  pinput: ^1.2.2
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.0
  geolocator: ^7.7.0
  geocoding: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - Images/
  fonts:
    - family: Segoe UI
      fonts:
        - asset: Fonts/Segoe UI.ttf
        - asset: Fonts/Segoe UI Bold.ttf